# Created by trellis-cli v1.6.0
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  imoveisdantas.com:
    site_hosts:
    - canonical: imoveisdantas.com
      redirects:
      - www.imoveisdantas.com
    local_path: ../site
    branch: master
    repo: git@github.com:dsemblano/imoveisdantas.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
